In [2]:
import pandas as pd
import folium

In [3]:
dfSepse = pd.read_csv('sepseCoord.csv', low_memory=False,delimiter=';', decimal=',')
dfSepse.head(10)

        Municipios  Obitos            Longitude             Latitude
0      Porto Velho     185           -63.831446            -8.768892
1    Guajará-Mirim       3           -65.323952  -10.773883999999999
2        Ariquemes      67           -63.033269   -9.908463000000001
3        Ji-Paraná      13  -61.945094999999995  -10.882050999999999
4           Cacoal      15           -61.442944  -11.433864999999999
5          Vilhena      25  -60.138583999999994           -12.741373
6  Cruzeiro do Sul       9           -72.672531  -7.6306899999999995
7       Rio Branco      29           -67.810529            -9.978299
8     Rio Negro AM       1  -49.797684999999994  -26.100407999999998
9            Juruá       1   -66.06304200000001  -3.4748900000000003

In [4]:
brasil = folium.Map(
    location=[-16.1237611, -59.9219642],
    zoom_start=4
)

In [5]:
brasil_com_pontos_sepse = brasil

for _, Municipio in dfSepse.iterrows():
    if (int(Municipio['Obitos']) >= 400) :
            c='crimson',
    elif (int(Municipio['Obitos']) <= 100) :
            c='yellow',
    else :
            c='orange',
    folium.CircleMarker(
        location=[float(Municipio['Latitude']), float(Municipio['Longitude'])],
        radius=3,
        color=c,  
        fill=True,
        fill_opacity=1.0,
        tooltip=str(Municipio['Obitos']),
        stroke=False
).add_to(brasil_com_pontos_sepse)

In [7]:
brasil_com_pontos_sepse.save('mapas_html/mapeamento_sepse.html')
# brasil_com_pontos_sepse

In [8]:
dfPneumo = pd.read_csv('Pneumocoord.csv', low_memory=False,delimiter=';', decimal=',')
dfPneumo.head(10)

        Municipios  Obitos   Longitude             Latitude
0       municipios       0           0                    0
1      Porto Velho     185  -63.831446            -8.768892
2    Guajará-Mirim       3  -65.323952  -10.773883999999999
3        Ariquemes      67  -63.033269   -9.908463000000001
4        Ji-Paraná      13  -61.945095  -10.882050999999999
5           Cacoal      15  -61.442944  -11.433864999999999
6          Vilhena      25  -60.138584           -12.741373
7  Cruzeiro do Sul       9  -72.672531  -7.6306899999999995
8       Rio Branco      29  -67.810529            -9.978299
9     Rio Negro AM       1  -49.797685  -26.100407999999998

In [9]:
brasil_com_pontos_pneumo = brasil

for _, Municipio in dfPneumo.iterrows():
    if (int(Municipio['Obitos']) >= 400) :
            c='darkpurple',
    elif (int(Municipio['Obitos']) <= 100) :
            c='lightgreen',
    else :
            c='cadetblue',
    folium.CircleMarker(
        location=[float(Municipio['Latitude']), float(Municipio['Longitude'])],
        radius=3,
        color=c,  
        fill=True,
        fill_opacity=1.0,
        tooltip=str(Municipio['Obitos']),
        stroke=False
).add_to(brasil_com_pontos_pneumo)

In [10]:
brasil_com_pontos_pneumo.save('mapas_html/mapeamento_pneumo.html')
# brasil_com_pontos_pneumo